version: 2.1

jobs:
  print_pipeline_id:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: echo $CIRCLE_WORKFLOW_ID
workflows:
  say-hello-workflow:
    jobs:
      - print_pipeline_id

