version: 2.1
commands:

jobs:
  simple_job:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: return 1
      - run: echo err
        when: on_fail

workflows:
  pipeline_workflow:
    jobs:
      - simple_job

