version: 2.1
commands:

jobs:
  simple_job:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: 
          command: return 1
      - run: 
          command: echo err
          when: on_fail

workflows:
  pipeline_workflow:
    jobs:
      - simple_job

