version: 2.1

jobs:
  say-hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello  > output.txt"
workflows:
  say-hello-workflow:
    jobs:
      - say-hello:

