version: 2.1
commands:
  print_pipeline_id:
    description: "Simple echo command"
    parameters:
      id:
        type: string
    steps:
      - run: echo << parameters.id >>
jobs:
  print_pipeline_id:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - print_pipeline_id

workflows:
  pipeline_workflow:
    jobs:
      - print_pipeline_id:
          id: << pipeline.id >>

